### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by 0xbaadf00d** [playframework/play-enhancer#13]
Hi @marcospereira ,

When the new version will be released ?

**Comment by mkurz** [comment]
Probably with Play 2.6 there will be a new release here as well.

**Comment by marcospereira** [comment]
1.2.0 and 1.2.1 were just released. They are virtually identical but need to do 1.2.1 because of a small problem while releasing.

@0xbaadf00d sorry for taking so long to do this release.
