### ISSUE TITLE
Handling of is* getters

### ISSUE THREAD

**Issue by timowest** [playframework/play-enhancer#7]
It looks like is\* getters aren't handled in PropertiesEnhancer. If they are ignored then getters are created for cases where is\* getters are available.

Could is\* getters be handled as well? I could provide PR if needed.

**Comment by jroper** [comment]
Yes, a PR fixing this would be welcomed.  Make sure you include tests (I think all the tests for this are scripted tests, they can be run using `sbt scripted`).

**Comment by mkurz** [comment]
@timowest Do you have some spare time to provide a PR?

**Comment by marcospereira** [comment]
Fixed in #12.
